<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReferentielMetierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $domains = [
            'A' => 'Agriculture et Pêche, Espaces naturels et Espaces verts, Soins aux animaux',
            'B' => 'Arts et Façonnage d\'ouvrages d\'art',
            'C' => 'Banque, Immobilier, Assurance',
            'D' => 'Commerce, Vente et Grande distribution',
            'E' => 'Communication, Média et Multimédia',
            'F' => 'Construction, Bâtiment et Travaux publics',
            'G' => 'Hôtellerie-Restauration, Tourisme, Loisirs et Animation',
            'H' => 'Industrie',
            'I' => 'Installation et Maintenance',
            'J' => 'Santé',
            'K' => 'Services à la personne et à la collectivité',
            'L' => 'Spectacle',
            'M' => 'Support à l\'entreprise',
            'N' => 'Transport et Logistique',
        ];

        $fiches = [
            // AGRICULTURE (A)
            ['A1101', 'Conduite d\'engins d\'exploitation agricole et forestière', 'A'],
            ['A1201', 'Bûcheronnage et élagage', 'A'],
            ['A1202', 'Entretien des espaces naturels', 'A'],
            ['A1203', 'Entretien des espaces verts', 'A'],
            ['A1204', 'Protection du patrimoine naturel', 'A'],
            ['A1205', 'Sylviculture', 'A'],
            ['A1301', 'Conseil et assistance technique en agriculture', 'A'],
            ['A1302', 'Contrôle et diagnostic technique en agriculture', 'A'],
            ['A1303', 'Ingénierie en agriculture et environnement', 'A'],
            ['A1401', 'Elevage d\'animaux de ferme', 'A'],
            ['A1402', 'Elevage d\'animaux de compagnie', 'A'],
            ['A1403', 'Elevage d\'équidés', 'A'],
            ['A1404', 'Entraînement d\'animaux', 'A'],
            ['A1405', 'Soins aux animaux', 'A'],
            ['A1406', 'Dressage d\'animaux', 'A'],
            ['A1407', 'Elevage de poissons, coquillages et crustacés', 'A'],
            ['A1408', 'Elevage de gibier', 'A'],
            ['A1409', 'Elevage d\'insectes et arachnides', 'A'],
            ['A1410', 'Elevage de reptiles et amphibiens', 'A'],
            ['A1411', 'Elevage de vers à soie', 'A'],
            ['A1501', 'Aide aux soins animaux', 'A'],
            ['A1502', 'Toilettage des animaux', 'A'],
            ['A1503', 'Assistance aux soins et vétérinaire', 'A'],

            // ARTS (B)
            ['B1101', 'Création en arts plastiques', 'B'],
            ['B1201', 'Réalisation d\'objets décoratifs et utilitaires en céramique et matériaux de synthèse', 'B'],
            ['B1301', 'Décoration d\'objets d\'art et artisanaux', 'B'],
            ['B1302', 'Reliure et restauration de livres et documents anciens', 'B'],
            ['B1303', 'Gravure d\'objets d\'art et artisanaux', 'B'],
            ['B1401', 'Réalisation d\'ouvrages en verre', 'B'],
            ['B1402', 'Taille et décoration de pierres', 'B'],
            ['B1501', 'Fabrication et réparation d\'instruments de musique', 'B'],
            ['B1601', 'Métallerie d\'art', 'B'],
            ['B1602', 'Bijouterie, joaillerie, orfèvrerie', 'B'],
            ['B1603', 'Réalisation d\'ouvrages en bronze', 'B'],
            ['B1604', 'Réalisation d\'ouvrages en fer forgé', 'B'],
            ['B1701', 'Horlogerie', 'B'],
            ['B1801', 'Réalisation d\'ouvrages en bois et matériaux associés', 'B'],
            ['B1802', 'Ebénisterie', 'B'],
            ['B1803', 'Luthiers et facteurs d\'instruments à cordes', 'B'],
            ['B1804', 'Marqueterie', 'B'],
            ['B1805', 'Sculpture sur bois', 'B'],
            ['B1806', 'Tapisserie d\'ameublement', 'B'],

            // BANQUE (C)
            ['C1101', 'Conception - développement de produits d\'assurance', 'C'],
            ['C1102', 'Conseil clientèle en assurances', 'C'],
            ['C1103', 'Courtage en assurances', 'C'],
            ['C1104', 'Direction d\'exploitation en assurances', 'C'],
            ['C1105', 'Expertise risques en assurances', 'C'],
            ['C1106', 'Gestion de portefeuilles de clients en assurances', 'C'],
            ['C1107', 'Indemnisation des sinistres', 'C'],
            ['C1108', 'Management de groupe en assurances', 'C'],
            ['C1109', 'Rédaction de contrats d\'assurances', 'C'],
            ['C1110', 'Souscription de risques en assurances', 'C'],
            ['C1201', 'Accueil et services bancaires', 'C'],
            ['C1202', 'Analyse de crédits et risques bancaires', 'C'],
            ['C1203', 'Relation clients banque finance', 'C'],
            ['C1204', 'Conception et expertise produits bancaires et financiers', 'C'],
            ['C1205', 'Conseil en gestion de patrimoine financier', 'C'],
            ['C1206', 'Gestion en banque et assurance', 'C'],
            ['C1207', 'Management de groupe et de secteur en banque', 'C'],
            ['C1301', 'Front office marchés financiers', 'C'],
            ['C1302', 'Gestion de portefeuilles actifs financiers', 'C'],
            ['C1303', 'Gestion back et middle-office marchés financiers', 'C'],
            ['C1401', 'Gestion locative immobilière', 'C'],
            ['C1501', 'Gérance immobilière', 'C'],
            ['C1502', 'Gestion de copropriété', 'C'],
            ['C1503', 'Management de projet immobilier', 'C'],
            ['C1504', 'Transaction immobilière', 'C'],

            // COMMERCE (D)
            ['D1101', 'Boucherie', 'D'],
            ['D1102', 'Boulangerie - pâtisserie', 'D'],
            ['D1103', 'Charcuterie - traiteur', 'D'],
            ['D1104', 'Pâtisserie, confiserie, chocolaterie et glacerie', 'D'],
            ['D1105', 'Poissonnerie', 'D'],
            ['D1106', 'Vente en alimentation', 'D'],
            ['D1107', 'Vente en boucherie', 'D'],
            ['D1201', 'Achat vente d\'objets d\'art, d\'antiquités ou de collection', 'D'],
            ['D1202', 'Coiffure', 'D'],
            ['D1203', 'Hydrothérapie', 'D'],
            ['D1204', 'Location d\'articles de sport et de loisirs', 'D'],
            ['D1205', 'Nettoyage d\'articles textiles ou cuir', 'D'],
            ['D1206', 'Réparation d\'articles en cuir et matériaux souples', 'D'],
            ['D1207', 'Soins esthétiques et corporels', 'D'],
            ['D1208', 'Soins oculaires', 'D'],
            ['D1209', 'Vente de végétaux', 'D'],
            ['D1210', 'Vente et location de véhicules', 'D'],
            ['D1211', 'Vente en articles de sport et de loisirs', 'D'],
            ['D1212', 'Vente en équipement du foyer', 'D'],
            ['D1213', 'Vente en habillement et accessoires de la personne', 'D'],
            ['D1214', 'Vente en parfumerie et cosmétique', 'D'],
            ['D1301', 'Management de magasin de détail', 'D'],
            ['D1401', 'Assistanat commercial', 'D'],
            ['D1402', 'Relation commerciale grands comptes et entreprises', 'D'],
            ['D1403', 'Relation commerciale auprès de particuliers', 'D'],
            ['D1404', 'Relation commerciale en vente à distance', 'D'],
            ['D1405', 'Conseil en information médicale', 'D'],
            ['D1406', 'Management en force de vente', 'D'],
            ['D1407', 'Relation technico-commerciale', 'D'],
            ['D1408', 'Téléconseil et télévente', 'D'],
            ['D1501', 'Animation de vente', 'D'],
            ['D1502', 'Management/gestion de rayon produits alimentaires', 'D'],
            ['D1503', 'Management/gestion de rayon produits non alimentaires', 'D'],
            ['D1504', 'Direction de magasin de grande distribution', 'D'],
            ['D1505', 'Marchandisage', 'D'],
            ['D1506', 'Marchandisage visuel', 'D'],
            ['D1507', 'Mise en rayon produits auto-distribués', 'D'],
            ['D1508', 'Promotion des ventes', 'D'],
            ['D1509', 'Management de département en grande distribution', 'D'],

            // COMMUNICATION (E)
            ['E1101', 'Animation de site multimédia', 'E'],
            ['E1102', 'Conception de contenus multimédias', 'E'],
            ['E1103', 'Communication', 'E'],
            ['E1104', 'Conception de produits façonnés', 'E'],
            ['E1105', 'Coordination d\'édition', 'E'],
            ['E1106', 'Journalisme et information média', 'E'],
            ['E1107', 'Organisation d\'évènements', 'E'],
            ['E1108', 'Publicité', 'E'],
            ['E1201', 'Photographie', 'E'],
            ['E1202', 'Production en laboratoire cinématographique', 'E'],
            ['E1203', 'Production en laboratoire photographique', 'E'],
            ['E1204', 'Projection cinéma', 'E'],
            ['E1205', 'Réalisation de contenus multimédias', 'E'],
            ['E1301', 'Conduite de machines d\'impression', 'E'],
            ['E1302', 'Conduite de machines de façonnage routage', 'E'],
            ['E1303', 'Encadrement des industries graphiques', 'E'],
            ['E1304', 'Prépresse', 'E'],
            ['E1305', 'Préparation et finition de produits imprimés', 'E'],
            ['E1306', 'Reprographie', 'E'],
            ['E1307', 'Sérigraphie', 'E'],
            ['E1308', 'Intervention technique en industrie graphique', 'E'],
            ['E1401', 'Développement et promotion de la librairie', 'E'],
            ['E1402', 'Élaboration de plan média', 'E'],

            // CONSTRUCTION (F)
            ['F1101', 'Architecture du BTP', 'F'],
            ['F1102', 'Conception - aménagement des espaces paysagers', 'F'],
            ['F1103', 'Contrôle et diagnostic technique du bâtiment', 'F'],
            ['F1104', 'Dessin BTP et paysage', 'F'],
            ['F1105', 'Études géologiques', 'F'],
            ['F1106', 'Ingénierie et études du BTP', 'F'],
            ['F1107', 'Mesures topographiques', 'F'],
            ['F1108', 'Métré de la construction', 'F'],
            ['F1201', 'Conduite de travaux du BTP', 'F'],
            ['F1202', 'Direction de chantier du BTP', 'F'],
            ['F1203', 'Direction et ingénierie d\'exploitation de gisements et de carrières', 'F'],
            ['F1204', 'Qualité Sécurité Environnement et Protection de la Santé du BTP', 'F'],
            ['F1301', 'Conduite d\'engins de terrassement et de carrière', 'F'],
            ['F1302', 'Conduite d\'engins de levage', 'F'],
            ['F1401', 'Extraction de minerais hors gisements', 'F'],
            ['F1402', 'Extraction de minerais sur gisements', 'F'],
            ['F1501', 'Montage de structures et de charpentes métalliques', 'F'],
            ['F1502', 'Montage de structures bois', 'F'],
            ['F1503', 'Réalisation - installation d\'ossatures bois', 'F'],
            ['F1601', 'Application et décoration en plâtre, stuc et staff', 'F'],
            ['F1602', 'Electricité bâtiment', 'F'],
            ['F1603', 'Installation d\'équipements sanitaires et thermiques', 'F'],
            ['F1604', 'Montage d\'agencements', 'F'],
            ['F1605', 'Montage de réseaux électriques et télécoms', 'F'],
            ['F1606', 'Peinture en bâtiment', 'F'],
            ['F1607', 'Pose de revêtements rigides', 'F'],
            ['F1608', 'Pose de revêtements souples', 'F'],
            ['F1609', 'Pose et restauration de couvertures', 'F'],
            ['F1610', 'Pose et restauration de menuiseries', 'F'],
            ['F1611', 'Réalisation et restauration de façades', 'F'],
            ['F1612', 'Taille et pose de pierres', 'F'],
            ['F1613', 'Travaux d\'étanchéité et d\'isolation', 'F'],
            ['F1701', 'Construction en béton', 'F'],
            ['F1702', 'Construction de routes et voies', 'F'],
            ['F1703', 'Maçonnerie', 'F'],
            ['F1704', 'Montage de structures et de charpentes bois', 'F'],
            ['F1705', 'Pose de canalisations', 'F'],
            ['F1706', 'Préfabrication en béton', 'F'],

            // HOTELLERIE / RESTAURATION (G)
            ['G1101', 'Accueil touristique', 'G'],
            ['G1102', 'Promotion du tourisme local', 'G'],
            ['G1201', 'Accompagnement de voyages, d\'activités culturelles ou sportives', 'G'],
            ['G1202', 'Animation d\'activités culturelles ou détente', 'G'],
            ['G1203', 'Animation de loisirs auprès d\'enfants ou d\'adolescents', 'G'],
            ['G1204', 'Éducation en activités sportives', 'G'],
            ['G1205', 'Personnel d\'attraction ou de manège', 'G'],
            ['G1206', 'Personnel d\'encadrement de l\'animation', 'G'],
            ['G1301', 'Conception de produits touristiques', 'G'],
            ['G1302', 'Optimisation de produits touristiques', 'G'],
            ['G1303', 'Vente de voyages', 'G'],
            ['G1401', 'Assistance de direction d\'hôtel-restaurant', 'G'],
            ['G1402', 'Management d\'hôtel-restaurant', 'G'],
            ['G1403', 'Gestion de structure de loisirs ou d\'hébergement touristique', 'G'],
            ['G1404', 'Management d\'établissement de restauration collective', 'G'],
            ['G1501', 'Personnel d\'étage', 'G'],
            ['G1502', 'Personnel polyvalent d\'hôtellerie', 'G'],
            ['G1503', 'Management du personnel d\'étage', 'G'],
            ['G1601', 'Management du service en restauration', 'G'],
            ['G1602', 'Personnel de cuisine', 'G'],
            ['G1603', 'Personnel polyvalent en restauration', 'G'],
            ['G1604', 'Fabrication de crêpes ou pizzas', 'G'],
            ['G1605', 'Plonge en restauration', 'G'],
            ['G1701', 'Conciergerie en hôtellerie', 'G'],
            ['G1702', 'Réception en hôtellerie', 'G'],
            ['G1703', 'Réception en établissement de soins', 'G'],
            ['G1801', 'Café, bar multimédia', 'G'],
            ['G1802', 'Management de bar ou brasserie', 'G'],
            ['G1803', 'Service en restauration', 'G'],

            // INDUSTRIE (H)
            ['H1101', 'Assistance et support technique client', 'H'],
            ['H1102', 'Management et ingénierie d\'affaires', 'H'],
            ['H1201', 'Expertise technique couleur en industrie', 'H'],
            ['H1202', 'Conception et dessin de produits mécaniques', 'H'],
            ['H1203', 'Conception et dessin produits électriques et électroniques', 'H'],
            ['H1204', 'Design industriel', 'H'],
            ['H1205', 'Études - méthodes en industrie', 'H'],
            ['H1206', 'Management et ingénierie études, recherche et développement industriel', 'H'],
            ['H1207', 'Rédaction technique', 'H'],
            ['H1208', 'Intervention technique en études et conception en automatisme', 'H'],
            ['H1209', 'Intervention technique en études et développement électronique', 'H'],
            ['H1210', 'Intervention technique en études, méthodes et préparation de la production', 'H'],
            ['H1301', 'Inspection de conformité', 'H'],
            ['H1302', 'Management et ingénierie Hygiène Sécurité Environnement -HSE- industriels', 'H'],
            ['H1303', 'Intervention technique en Hygiène Sécurité Environnement -HSE- industriel', 'H'],
            ['H1401', 'Management et ingénierie gestion industrielle et logistique', 'H'],
            ['H1402', 'Management et ingénierie méthodes et industrialisation', 'H'],
            ['H1403', 'Intervention technique en gestion industrielle et logistique', 'H'],
            ['H1404', 'Intervention technique en méthodes et industrialisation', 'H'],
            ['H1501', 'Direction d\'exploitation industrielle', 'H'],
            ['H1502', 'Management et ingénierie de production', 'H'],
            ['H1503', 'Intervention technique en HSE industriel', 'H'],
            ['H1504', 'Intervention technique en méthodes et industrialisation', 'H'],
            ['H1505', 'Intervention technique en gestion industrielle et logistique', 'H'],
            ['H1506', 'Intervention technique en production de métaux non ferreux', 'H'],
            ['H2101', 'Abattage et découpe des viandes', 'H'],
            ['H2102', 'Conduite d\'équipement de production alimentaire', 'H'],
            ['H2103', 'Contrôle et diagnostic technique en industrie agroalimentaire', 'H'],
            ['H2104', 'Préparation de matières et produits agricoles (nettoyage, décortiquage, ...)', 'H'],
            ['H2105', 'Intervention technique en industrie agroalimentaire', 'H'],
            ['H2201', 'Ajustage et montage de fabrication', 'H'],
            ['H2202', 'Conduite d\'équipement de fabrication de l\'ameublement et du bois', 'H'],
            ['H2203', 'Conduite d\'équipement de transformation du verre', 'H'],
            ['H2204', 'Encadrement des industries de l\'ameublement et du bois', 'H'],
            ['H2205', 'Intervention technique en ameublement et bois', 'H'],
            ['H2206', 'Réalisation de menuiserie bois et tonnellerie', 'H'],
            ['H2207', 'Réalisation de meubles en bois', 'H'],
            ['H2208', 'Réalisation d\'ouvrages décoratifs en bois', 'H'],
            ['H2209', 'Intervention technique en ameublement et bois', 'H'],
            ['H2301', 'Conduite d\'équipement de production chimique ou pharmaceutique', 'H'],
            ['H2401', 'Assemblage - montage d\'articles en cuirs ou matériaux souples', 'H'],
            ['H2402', 'Conduite de machine de fabrication de produits textiles', 'H'],
            ['H2403', 'Conduite de machine de traitement textile', 'H'],
            ['H2404', 'Conduite de machine de transformation des cuirs et peaux', 'H'],
            ['H2405', 'Confection de vêtements et accessoires en cuir ou matériaux souples', 'H'],
            ['H2406', 'Découpe de cuirs et peaux', 'H'],
            ['H2407', 'Réalisation de vêtements sur mesure ou en petite série', 'H'],
            ['H2408', 'Réparation d\'articles en cuir et matériaux souples', 'H'],
            ['H2409', 'Tannerie - mégisserie', 'H'],
            ['H2410', 'Intervention technique en industrie textile et cuir', 'H'],
            ['H2411', 'Intervention technique en production de vêtements', 'H'],
            ['H2412', 'Intervention technique en traitement textile et cuir', 'H'],
            ['H2413', 'Intervention technique en transformation des cuirs et peaux', 'H'],
            ['H2501', 'Application de couches de protection et de revêtement sur métaux', 'H'],
            ['H2502', 'Conduite d\'équipement de fabrication des métaux', 'H'],
            ['H2503', 'Conduite d\'équipement d\'usinage', 'H'],
            ['H2504', 'Encadrement d\'équipe en industrie de transformation des métaux', 'H'],
            ['H2505', 'Intervention technique en fonderie', 'H'],
            ['H2601', 'Conduite d\'équipement de mise en forme des plastiques et caoutchoucs', 'H'],
            ['H2701', 'Pilotage d\'installation de production de papier et carton', 'H'],
            ['H2801', 'Conduite d\'équipement de transformation du verre', 'H'],
            ['H2901', 'Ajustage et montage de fabrication', 'H'],
            ['H2902', 'Chaudronnerie - tôlerie', 'H'],
            ['H2903', 'Conduite d\'équipement de formage et découpage des métaux', 'H'],
            ['H2904', 'Dinandier', 'H'],
            ['H2905', 'Ebavurage des métaux', 'H'],
            ['H2906', 'Forgeage manuel', 'H'],
            ['H2907', 'Intervention technique en fonderie', 'H'],
            ['H2908', 'Modelage de matériaux non métalliques', 'H'],
            ['H2909', 'Montage-assemblage mécanique', 'H'],
            ['H2910', 'Moulage sablerie noyautage mécanique', 'H'],
            ['H2911', 'Réalisation de structures métalliques', 'H'],
            ['H2912', 'Réglage d\'équipement de fabrication industrielle', 'H'],
            ['H2913', 'Soudage manuel', 'H'],
            ['H2914', 'Réalisation et montage d\'équipements industriels et d\'exploitation', 'H'],
            ['H3101', 'Conduite d\'équipement d\'usinage des métaux', 'H'],
            ['H3102', 'Conduite d\'installation de production de métaux non ferreux', 'H'],
            ['H3201', 'Conduite d\'équipement de formage et découpage des métaux', 'H'],
            ['H3301', 'Conduite d\'équipement de conditionnement', 'H'],
            ['H3302', 'Opérations manuelles d\'assemblage, triage ou emballage', 'H'],
            ['H3401', 'Conduite d\'équipement de déformation des métaux', 'H'],

            // INSTALLATION / MAINTENANCE (I)
            ['I1101', 'Direction et ingénierie de maintenance industrielle', 'I'],
            ['I1102', 'Management et ingénierie de maintenance industrielle', 'I'],
            ['I1103', 'Supervision d\'entretien et maintenance immobilière', 'I'],
            ['I1201', 'Entretien d\'affichage et mobilier urbain', 'I'],
            ['I1202', 'Entretien et surveillance du tracé routier', 'I'],
            ['I1203', 'Maintenance des bâtiments et locaux', 'I'],
            ['I1301', 'Installation et maintenance d\'ascenseurs', 'I'],
            ['I1302', 'Installation et maintenance d\'automatismes', 'I'],
            ['I1303', 'Installation et maintenance de distributeurs automatiques', 'I'],
            ['I1304', 'Installation et maintenance d\'équipements industriels et d\'exploitation', 'I'],
            ['I1305', 'Installation et maintenance électronique', 'I'],
            ['I1306', 'Installation et maintenance en froid, conditionnement d\'air', 'I'],
            ['I1307', 'Installation et maintenance télécoms et courants faibles', 'I'],
            ['I1308', 'Maintenance électrique', 'I'],
            ['I1309', 'Maintenance mécanique industrielle', 'I'],
            ['I1310', 'Maintenance et réparation en micro-mécanique', 'I'],
            ['I1401', 'Maintenance informatique et bureautique', 'I'],
            ['I1402', 'Réparation de biens électrodomestiques', 'I'],
            ['I1501', 'Intervention en grande hauteur', 'I'],
            ['I1502', 'Intervention en milieu subaquatique', 'I'],
            ['I1503', 'Intervention en milieux et produits nocifs', 'I'],
            ['I1601', 'Installation et maintenance de piscines', 'I'],
            ['I1602', 'Maintenance d\'aéronefs', 'I'],
            ['I1603', 'Maintenance d\'engins de chantier, levage, manutention et de machines agricoles', 'I'],
            ['I1604', 'Mécanique de marine', 'I'],
            ['I1605', 'Mécanique de précision et horlogerie', 'I'],
            ['I1606', 'Réparation de cycles et motocycles', 'I'],
            ['I1607', 'Réparation de carrosserie', 'I'],

            // SANTE (J)
            ['J1101', 'Cabinet médical', 'J'],
            ['J1102', 'Médecine généraliste et spécialisée', 'J'],
            ['J1103', 'Médecine dentaire', 'J'],
            ['J1104', 'Pharmacie', 'J'],
            ['J1201', 'Biologie médicale', 'J'],
            ['J1301', 'Personnel polyvalent des services hospitaliers', 'J'],
            ['J1302', 'Sages-femmes', 'J'],
            ['J1401', 'Audioprothèse', 'J'],
            ['J1402', 'Diététique', 'J'],
            ['J1403', 'Ergothérapie', 'J'],
            ['J1404', 'Kinésithérapie', 'J'],
            ['J1405', 'Optique - lunetterie', 'J'],
            ['J1406', 'Orthophonie', 'J'],
            ['J1407', 'Orthoptique', 'J'],
            ['J1408', 'Ostéopathie et chiropraxie', 'J'],
            ['J1409', 'Pédicurie et podologie', 'J'],
            ['J1410', 'Prothèses dentaires', 'J'],
            ['J1411', 'Prothèses et orthèses médicales', 'J'],
            ['J1412', 'Psychomotricité', 'J'],
            ['J1501', 'Aide en puériculture', 'J'],
            ['J1502', 'Coordination de services médicaux ou paramédicaux', 'J'],
            ['J1503', 'Infirmier / Infirmière en soins généraux', 'J'],
            ['J1504', 'Infirmier / Infirmière spécialisé(e) en anesthésie', 'J'],
            ['J1505', 'Infirmier / Infirmière spécialisé(e) en bloc opératoire', 'J'],
            ['J1506', 'Infirmier / Infirmière spécialisé(e) en puériculture', 'J'],
            ['J1507', 'Soins d\'hygiène, de confort du patient', 'J'],

            // SERVICES (K)
            ['K1101', 'Accompagnement et médiation sociale', 'K'],
            ['K1102', 'Aide aux personnes âgées', 'K'],
            ['K1103', 'Aide aux personnes handicapées', 'K'],
            ['K1104', 'Psychologie', 'K'],
            ['K1201', 'Action sociale', 'K'],
            ['K1202', 'Éducation spécialisée', 'K'],
            ['K1203', 'Encadrement de structure d\'accueil de jeunes enfants', 'K'],
            ['K1204', 'Médiation sociale et facilitation de la vie en quartier', 'K'],
            ['K1205', 'Protection des personnes', 'K'],
            ['K1206', 'Enseignement général du second degré', 'K'],
            ['K1207', 'Intervention socio-éducative', 'K'],
            ['K1301', 'Accompagnement de personnes en difficulté', 'K'],
            ['K1302', 'Assistance de vie', 'K'],
            ['K1303', 'Assistance auprès d\'enfants', 'K'],
            ['K1304', 'Services domestiques', 'K'],
            ['K1305', 'Intervention sociale et familiale', 'K'],
            ['K1401', 'Conception et pilotage de la formation professionnelle', 'K'],
            ['K1402', 'Conseil en formation', 'K'],
            ['K1403', 'Management de structure de formation', 'K'],
            ['K1404', 'Formation professionnelle', 'K'],
            ['K1405', 'Enseignement technique et professionnel', 'K'],
            ['K1501', 'Application des règles de justice', 'K'],
            ['K1502', 'Assistance auprès de magistrats', 'K'],
            ['K1503', 'Droit', 'K'],
            ['K1504', 'Magistrature', 'K'],
            ['K1505', 'Greffe de tribunal', 'K'],
            ['K1601', 'Gestion de l\'information et de la documentation', 'K'],
            ['K1602', 'Gestion de patrimoine culturel', 'K'],
            ['K1701', 'Personnel de la Défense', 'K'],
            ['K1702', 'Sécurité publique', 'K'],
            ['K1703', 'Surveillance et protection de locaux', 'K'],
            ['K1704', 'Sécurité civile et secours', 'K'],
            ['K1705', 'Convoyage de fonds et de valeurs', 'K'],
            ['K1706', 'Sécurité et surveillance privée', 'K'],
            ['K1707', 'Intervention en milieu pénitentiaire', 'K'],
            ['K1801', 'Conseil en emploi et insertion professionnelle', 'K'],
            ['K1802', 'Développement local', 'K'],
            ['K1901', 'Aide et médiation sociale', 'K'],
            ['K1902', 'Collaboration juridique', 'K'],
            ['K2101', 'Conseil en formation', 'K'],
            ['K2102', 'Coordination pédagogique', 'K'],
            ['K2103', 'Direction d\'établissement d\'enseignement', 'K'],
            ['K2104', 'Enseignement d\'art', 'K'],
            ['K2105', 'Enseignement de la conduite', 'K'],
            ['K2106', 'Enseignement des écoles', 'K'],
            ['K2107', 'Enseignement général du second degré', 'K'],
            ['K2108', 'Enseignement supérieur', 'K'],
            ['K2109', 'Enseignement technique et professionnel', 'K'],
            ['K2110', 'Formation professionnelle', 'K'],
            ['K2111', 'Formation en conduite d\'engins', 'K'],
            ['K2112', 'Orientation scolaire et professionnelle', 'K'],

            // SPECTACLE (L)
            ['L1101', 'Animation de spectacles', 'L'],
            ['L1102', 'Mannequinat et pose artistique', 'L'],
            ['L1103', 'Présentation de spectacles ou d\'émissions', 'L'],
            ['L1201', 'Danse', 'L'],
            ['L1202', 'Musique et chant', 'L'],
            ['L1203', 'Art dramatique', 'L'],
            ['L1204', 'Arts du cirque et spectacles visuels', 'L'],
            ['L1301', 'Conception de décors et d\'espaces', 'L'],
            ['L1302', 'Conception et réalisation de costumes', 'L'],
            ['L1303', 'Création de supports visuels', 'L'],
            ['L1304', 'Réalisation cinématographique et audiovisuelle', 'L'],
            ['L1401', 'Gestion de structures culturelles et d\'information', 'L'],
            ['L1501', 'Direction de production audiovisuelle, cinématographique et spectacle', 'L'],
            ['L1502', 'Régie générale audiovisuelle, cinématographique et spectacle', 'L'],
            ['L1503', 'Scripte', 'L'],
            ['L1504', 'Eclairage de spectacle', 'L'],
            ['L1505', 'Image cinématographique et télévisuelle', 'L'],
            ['L1506', 'Machinerie de spectacle', 'L'],
            ['L1507', 'Montage et post-production', 'L'],
            ['L1508', 'Prise de son et sonorisation', 'L'],
            ['L1509', 'Maquillage et coiffure de spectacle', 'L'],

            // SUPPORT ENTREPRISE (M)
            ['M1101', 'Achats', 'M'],
            ['M1102', 'Direction des achats', 'M'],
            ['M1201', 'Analyse et ingénierie financière', 'M'],
            ['M1202', 'Audit et contrôle comptables et financiers', 'M'],
            ['M1203', 'Comptabilité', 'M'],
            ['M1204', 'Contrôle de gestion', 'M'],
            ['M1205', 'Direction administrative et financière', 'M'],
            ['M1206', 'Management de groupe ou de service comptable et financier', 'M'],
            ['M1207', 'Trésorerie et financement', 'M'],
            ['M1301', 'Direction de grande entreprise ou d\'établissement public', 'M'],
            ['M1302', 'Direction de petite ou moyenne entreprise', 'M'],
            ['M1401', 'Conduite d\'enquêtes', 'M'],
            ['M1402', 'Conseil en organisation et management d\'entreprise', 'M'],
            ['M1403', 'Études et analyses de marchés', 'M'],
            ['M1404', 'Management de la qualité', 'M'],
            ['M1501', 'Assistanat en ressources humaines', 'M'],
            ['M1502', 'Développement des ressources humaines', 'M'],
            ['M1503', 'Management des ressources humaines', 'M'],
            ['M1601', 'Assistanat en communication', 'M'],
            ['M1602', 'Opérations administratives', 'M'],
            ['M1603', 'Secrétariat', 'M'],
            ['M1604', 'Assistanat de direction', 'M'],
            ['M1605', 'Assistanat technique et administratif', 'M'],
            ['M1606', 'Saisie de données', 'M'],
            ['M1607', 'Accueil et orientation', 'M'],
            ['M1608', 'Secrétariat comptable', 'M'],
            ['M1609', 'Secrétariat juridique', 'M'],
            ['M1701', 'Administration de systèmes d\'information', 'M'],
            ['M1702', 'Analyse de systèmes d\'information', 'M'],
            ['M1703', 'Management de projet informatique', 'M'],
            ['M1704', 'Management de systèmes d\'information', 'M'],
            ['M1705', 'Conseil et maîtrise d\'ouvrage en systèmes d\'information', 'M'],
            ['M1801', 'Administration de systèmes, réseaux et télécoms', 'M'],
            ['M1802', 'Expertise et support technique en systèmes d\'information', 'M'],
            ['M1803', 'Direction des systèmes d\'information', 'M'],
            ['M1804', 'Études et développement de réseaux de télécoms', 'M'],
            ['M1805', 'Études et développement informatique', 'M'],
            ['M1806', 'Expertise et conseil en systèmes d\'information', 'M'],

            // TRANSPORT (N)
            ['N1101', 'Conduite d\'engins de déplacement des charges', 'N'],
            ['N1102', 'Conduite d\'engins de transport de marchandises', 'N'],
            ['N1103', 'Magasinage et préparation de commandes', 'N'],
            ['N1104', 'Manutention manuelle de charges', 'N'],
            ['N1105', 'Manutention portuaire', 'N'],
            ['N1201', 'Affrètement transport', 'N'],
            ['N1202', 'Gestion des opérations de circulation internationale des marchandises', 'N'],
            ['N1301', 'Conception et organisation de la chaîne logistique', 'N'],
            ['N1302', 'Direction de site logistique', 'N'],
            ['N1303', 'Intervention technique d\'exploitation logistique', 'N'],
            ['N2101', 'Navigation commerciale aérienne', 'N'],
            ['N2102', 'Pilotage d\'aéronefs', 'N'],
            ['N2201', 'Personnel d\'escale aéroportuaire', 'N'],
            ['N2202', 'Personnel de piste aéroportuaire', 'N'],
            ['N2203', 'Sécurité et surveillance aéroportuaire', 'N'],
            ['N2204', 'Préparation des vols', 'N'],
            ['N2205', 'Direction d\'escale aéroportuaire', 'N'],
            ['N3101', 'Conduite de transport de marchandises sur longue distance', 'N'],
            ['N3102', 'Conduite de transport de marchandises sur courte distance', 'N'],
            ['N3103', 'Déménagement', 'N'],
            ['N3201', 'Conduite de transport en commun sur route', 'N'],
            ['N3202', 'Conduite de transport de particuliers', 'N'],
            ['N3203', 'Livreur / Livreuse de marchandises', 'N'],
            ['N4101', 'Conduite de transport de marchandises sur longue distance', 'N'],
            ['N4102', 'Conduite de transport de marchandises sur courte distance', 'N'],
            ['N4103', 'Conduite de transport de particuliers', 'N'],
            ['N4104', 'Courses et livraisons express', 'N'],
            ['N4105', 'Déménagement', 'N'],
            ['N4201', 'Direction d\'exploitation de transport routier de marchandises', 'N'],
            ['N4202', 'Direction d\'exploitation de transport routier de personnes', 'N'],
            ['N4203', 'Intervention technique d\'exploitation des transports routiers', 'N'],
            ['N4301', 'Conduite d\'engins de transport ferroviaire', 'N'],
            ['N4302', 'Contrôle des transports ferroviaires', 'N'],
            ['N4401', 'Circulation du transport ferroviaire', 'N'],
            ['N4402', 'Exploitation et manœuvre ferroviaire', 'N'],
            ['N4403', 'Relation clients ferroviaire', 'N'],
        ];

        foreach ($fiches as $fiche) {
            \App\Models\ReferentielMetier::updateOrCreate(
                ['code' => $fiche[0]],
                [
                    'title' => $fiche[1],
                    'family_name' => $domains[$fiche[2]] ?? 'Autre',
                    'description' => "Fiche métier ROME {$fiche[0]} : {$fiche[1]}",
                    'is_active' => true,
                ]
            );
        }
    }
}
